name: "Build Image"
on:
  push:
    branches: master
    paths: ["Dockerfile"]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/irq0/org-knit-action:v0.4
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
