on: [push]

jobs:
  Knit:
    runs-on: ubuntu-latest
    name: A little test knit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Export org files
        uses: ./
        with:
          export: html, pdf, md
          tangle: true
          keep_files: false
